### PR TITLE
use new enum encoding for client type

### LINKED ISSUE #34: Change names of client type values from presence data
We've overlooked one place when we were applying our naming convention for enum values https://github.com/ably/ably-asset-tracking-js/issues/32.

The client types sent in the `PresenceData` are currently written in lowercase `"subscriber", "publisher"`. We should change it to `"SUBSCRIBER", "PUBLISHER"`.

We should be extra careful with this change as **it will break the compatibility with older SDK versions as well as other platforms** (the other platforms will start working as soon as they make this change on their sides too).

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-821) by [Unito](https://www.unito.io)

### PR DESCRIPTION
**Pull request by owenpearson**
resolved #34.

### CODE REVIEW

**Comment by KacperKluka** [comment]
@owenpearson as I've written in the issue https://github.com/ably/ably-asset-tracking-js/issues/34 merging this will break the compatibility with Android and iOS apps because those changes are not present there :wink: So I don't think that we should land this PR at the moment :wink:

**Comment by QuintinWillison** [comment]
@KacperKluka What should be the trigger to enable this PR to land?

**Comment by KacperKluka** [comment]
@QuintinWillison Ideally both [Android](https://github.com/ably/ably-asset-tracking-android/issues/300) and [iOS](https://github.com/ably/ably-asset-tracking-cocoa/issues/136) issues should be closed together with this JS issue. Otherwise, the mobile SDKs will crash when a JS subscriber will be trying to subscribe for a trackable they are publishing.

**Comment by KacperKluka** [comment]
Android PR is ready https://github.com/ably/ably-asset-tracking-android/pull/310 so we can progress with this PR too :grin:

**Review by KacperKluka — APPROVED** [review]
Looks good :+1:

**Review by QuintinWillison — APPROVED** [review]

**Pull request merged**
